# Generated by Django 3.2.4 on 2021-12-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210828_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_home',
            field=models.BooleanField(default=True),
        ),
    ]
